### ISSUE TITLE
A Lot of Errors

### ISSUE THREAD

**Issue by Tartarus6** [absoluteAquarian/TerraScience#7]
When I tried to compile the mod it gave me error CS0234, meaning I'm missing some assembly references.  How do I get them.

In total I'm missing:
Collections
Diagnostics
IO
ComponentModel
Reflection
Linq
Text

here's the client.log file:
[errors.log](https://github.com/absoluteAquarian/TerraScience/files/8056664/errors.log)

**Comment by absoluteAquarian** [comment]
Which branch did you try to build?
If it's `master`, make sure that you have installed Visual Studio 2019 Community and its **.NET Desktop development** package.
If it's `1.4`, don't build that branch.  I haven't worked on it for several months.

**Comment by Tartarus6** [comment]
i had the wrong visual studio version. ill see if i can get it working. and yes, it was master

**Comment by Tartarus6** [comment]
i think that error was fixed. but now it's saying that i need a file called tModLoader.FNA.exe, i looked in the path that it said ("C:\Program Files (x86)\Steam\steamapps\common\tModLoader\ModCompile") and the closest thing i have was tModLoader.XNA.exe.

**Comment by absoluteAquarian** [comment]
Close the game, delete that ModCompile folder and then redownload it ingame when tML prompts you to do so.
Also, make sure that you're trying to build the mod on **32-bit tModLoader**, not 64-bit tModLoader.

**Comment by Tartarus6** [comment]
that worked, thx so much.

**Comment by Tartarus6** [comment]
this mod looks so cool
